Guard against breaking replication with DML in bdr.replicate_ddl_command
It's never correct to put DML in bdr.replicate_ddl_command. At best you'll
get conflicts, if your DML UPDATEs or DELETEs data in a table using only
immutable expressions.

More likely you'll get duplicate data if you do INSERTs, because it gets
replicated once as a statement and again as a decoded row change. The two
rows might be different if you use sequences, volatile functions, etc.

Worse, if your DML is mixed with DDL, you can break replication. For example,

bdr.bdr_replicate_ddl_command($DDL$
    ALTER TABLE t1 ADD COLUMN foo integer;
    UPDATE t1 SET foo = bar;
    ALTER TABLE t1 DROP COLUMN bar;
$DDL$);

will break replication with the error

    ERROR: data for dropped column

because BDR applies the whole compound SQL statement string from
bdr.bdr_replicate_ddl_command. Then it decodes the UPDATEd rows,
and tries to send them to the downstream. But the downstream already
applied the whole SQL statement string... so the target column 'bar'
doesn't exist anymore. Splat!

There's no safe way to handle this. If we suppressed logical decoding of rows
generated during a bdr.bdr_replicate_ddl_command, we'd introduce the issues
seen in statement-based replication with volatile functions etc instead.
As if we were permitting full table rewrites.

So simply disallow DML in bdr.bdr_replicate_ddl_command. It will now fail with
a message like

    ERROR:  row-data-modifying statements INSERT, UPDATE and DELETE are not permitted inside bdr.replicate_ddl_command
    HINT:  Split up scripts, putting DDL in bdr.replicate_ddl_command and DML as normal statements

Docs for bdr.bdr_replicate_ddl_command updated accordingly.