Improve error message when attempting to join a node before group is created
Currently, if bdr_group_join is executed with 'join_using_dsn'
pointing to an uninitialised BDR node, following error is displayed:

    ERROR:  remote node does not appear to be a fully running BDR node
    DETAIL:  The dsn ... connects successfully but the target node has bdr.bdr_nodes node_status= instead of expected 'r'

Patch checks if 'node_status' is NULL and issues a more informative DETAIL message.